
- set_fact:
    app_version: "{{ hostvars[inventory_hostname]['laclasse_' + application + '_version'] }}"
    app_key: "{{ laclasse_services[application]['api_key'] }}"
    app_id: "{{ laclasse_services[application]['app_id'] }}"
    app_path: "{{ laclasse_services[application]['path'] }}"
    app_title: "{{ laclasse_services[application]['title'] }}"
    app_description: "{{ laclasse_services[application]['description'] }}"
  tags:
    - laclasse
    - laclasse:register

- set_fact: app_ressource_url="{{ laclasse_main_url + '/' + app_path }}"
- set_fact: __app_ressource_url_sanitized="/{{ app_path }}/"
- set_fact: app_ressource_url_sanitized='{{ __app_ressource_url_sanitized | regex_replace("\/+", "/")}}'
  #    app_ressource_url_sanitized: '{{ app_ressource_url | regex_replace("\/+", "/") | regex_replace(":\/", "://") }}'
#    app_ressource_url_sanitized: "{{ app_ressource_url }}"

- debug: msg="{{ item }}"
  with_items:
    - app_version
    - app_key
    - app_id
    - app_path
    - app_title
    - app_description
    - app_ressource_url
  tags:
    - laclasse
    - laclasse:register

